version: '3.8'

services:
  master:
    # https://hub.docker.com/r/bitnami/spark/
    image: bitnami/spark:3.5
    hostname: master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "18080:8080"  # Spark Master Web UI
      - "17077:7077"  # Spark Master Port
      - "14040:4040"  # Spark Application Web UI
    networks:
      - spark-network

  worker-1:
    # https://hub.docker.com/r/bitnami/spark/
    image: bitnami/spark:3.5
    hostname: worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=16g
      - SPARK_WORKER_CORES=16
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "18081:8081"  # Spark Worker Web UI
    depends_on:
      - master
    networks:
      - spark-network

  worker-2:
    # https://hub.docker.com/r/bitnami/spark/
    image: bitnami/spark:3.5
    hostname: worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=16g
      - SPARK_WORKER_CORES=16
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "18082:8081"  # Spark Worker Web UI
    depends_on:
      - master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
